name: Auto PR for Feature Branches

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v7.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ github.ref_name }}
          title: "Auto PR - ${{ github.ref_name }}"
          body: |
            Automatically created pull request for the branch `${{ github.ref_name }}`
